name: docs-environment
channels:
  - pytorch
  - nvidia
  - conda-forge
  - salilab
  - plotly
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - mdanalysis
  - modeller
  - cctbx
  - pandas
  - scipy
  - pytorch
  - pytorch-cuda=12.1
  - biobox
  - openmm
  - ipywidgets
  - plotly
  - nglview
  - openmmtorchplugin
  - mdtraj
  - pip:
    - geomloss
